repository:
  security:
    enableVulnerabilityAlerts: true
    enableAutomatedSecurityFixes: true

  private: true
  visibility: private
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  allow_update_branch: true
  archived: false
labels:
  # Labels: define labels for Issues and Pull Requests
  include:
  #build, chore, ci, docs, perf, refactor, test, dependencies
    - name: fix
    - name: feat
    - name: build
    - name: chore
    - name: ci
    - name: docs
    - name: perf
    - name: refactor
    - name: test
    - name: dependencies
