name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter:
          - eslint
          - prettier
          - types
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2

      - name: Run JQ lint
        uses: home-assistant/actions/helpers/jq@master

      - name: Set NodeJS version
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: npm install

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2

      - name: Set NodeJS version
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test
