name: Require Pull Request Labels

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened
      - labeled
      - unlabeled

concurrency:
  group: require-label-${{ github.ref }}
  cancel-in-progress: true

jobs:
  require-label:
    name: Require Pull Request Labels
    runs-on: ubuntu-latest
    steps:
      - name: Check the labels
        uses: ludeeus/action-require-labels@1.1.0
        with:
          labels: >-
            build, chore, ci, docs, feat, fix, perf, refactor, test, dependencies
